# Unified KMS MCP Server - Standalone (uses PaaS databases)

services:
  # Main MCP Server
  unified-kms:
    build: .
    ports:
      - "3001:3001"
    env_file:
      - .env.cloud
    environment:
      # Transport Configuration
      TRANSPORT_MODE: http
      HTTP_PORT: 3001
      HTTP_HOST: 0.0.0.0
      
      # Use PaaS databases (configured in .env.cloud)
      MONGODB_URI: ${MONGODB_ATLAS_URI}
      MONGODB_DATABASE: unified_kms
      NEO4J_URI: ${NEO4J_AURA_URI}
      NEO4J_USERNAME: ${NEO4J_AURA_USERNAME}
      NEO4J_PASSWORD: ${NEO4J_AURA_PASSWORD}
      REDIS_URI: ${REDIS_CLOUD_URI}
      REDIS_CLOUD_URI: ${REDIS_CLOUD_URI}
      
      # Required API Keys
      MEM0_API_KEY: "m0-tHr9zMo9Mgx7CkTw0mHIiDZj65PDq047x1pfLbP7"
      MEM0_ORG_ID: "org_YT0a8tXkuhlEqGkaE5GS5pJF9WCoHjreOROTyGhg"
      MEM0_DEFAULT_USER_ID: "richard_yaker"
      MEM0_TELEMETRY: "false"
      
      # FACT Cache Configuration
      FACT_L1_SIZE: 104857600  # 100MB
      FACT_L2_TTL: 1800000     # 30 minutes
      FACT_L3_TTL: 3600000     # 1 hour
      
      # CORS & Security
      CORS_ORIGIN: "*"
      CORS_CREDENTIALS: "true"
      RATE_LIMIT_WINDOW: 900000  # 15 minutes
      RATE_LIMIT_MAX: 1000
      
      # OAuth 2.1 Configuration
      OAUTH_ENABLED: "false"
      OAUTH_ISSUER: ${OAUTH_ISSUER}
      OAUTH_AUDIENCE: ${OAUTH_AUDIENCE}
      OAUTH_JWKS_URI: ${OAUTH_JWKS_URI}
      OAUTH_CLIENT_ID: ${OAUTH_CLIENT_ID}
      OAUTH_CLIENT_SECRET: ${OAUTH_CLIENT_SECRET}
      OAUTH_AUTHORIZATION_ENDPOINT: ${OAUTH_AUTHORIZATION_ENDPOINT}
      OAUTH_TOKEN_ENDPOINT: ${OAUTH_TOKEN_ENDPOINT}
      OAUTH_TOKEN_INTROSPECTION_ENDPOINT: ${OAUTH_TOKEN_INTROSPECTION_ENDPOINT}
      
      NODE_ENV: production
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "-e", "fetch('http://localhost:3001/health').then(r=>r.ok?process.exit(0):process.exit(1)).catch(()=>process.exit(1))"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s