# Unified KMS MCP Server - Cloud PaaS Configuration
# Uses cloud-hosted databases instead of local containers
version: '3.8'

services:
  # Main MCP Server (connects to cloud databases)
  unified-kms:
    build: .
    ports:
      - "3001:3001"
    environment:
      # Transport Configuration
      TRANSPORT_MODE: http
      HTTP_PORT: 3001
      HTTP_HOST: 0.0.0.0
      
      # Cloud Database Connections
      MONGODB_URI: ${MONGODB_ATLAS_URI}                    # MongoDB Atlas
      MONGODB_DATABASE: ${MONGODB_DATABASE:-unified_kms}
      NEO4J_URI: ${NEO4J_AURA_URI}                        # Neo4j AuraDB  
      NEO4J_USERNAME: ${NEO4J_AURA_USERNAME}
      NEO4J_PASSWORD: ${NEO4J_AURA_PASSWORD}
      REDIS_URI: ${REDIS_CLOUD_URI}                       # Redis Cloud
      
      # Required API Keys
      MEM0_API_KEY: ${MEM0_API_KEY}
      MEM0_ORG_ID: ${MEM0_ORG_ID}
      
      # FACT Cache Configuration
      FACT_L1_SIZE: 104857600  # 100MB
      FACT_L2_TTL: 1800000     # 30 minutes
      FACT_L3_TTL: 3600000     # 1 hour
      
      # CORS & Security
      CORS_ORIGIN: ${CORS_ORIGIN:-*}
      CORS_CREDENTIALS: "true"
      RATE_LIMIT_WINDOW: 900000  # 15 minutes
      RATE_LIMIT_MAX: 1000
      
      # OAuth 2.1 Configuration
      OAUTH_ENABLED: ${OAUTH_ENABLED:-false}
      OAUTH_ISSUER: ${OAUTH_ISSUER}
      OAUTH_AUDIENCE: ${OAUTH_AUDIENCE}
      OAUTH_JWKS_URI: ${OAUTH_JWKS_URI}
      OAUTH_CLIENT_ID: ${OAUTH_CLIENT_ID}
      OAUTH_CLIENT_SECRET: ${OAUTH_CLIENT_SECRET}
      OAUTH_AUTHORIZATION_ENDPOINT: ${OAUTH_AUTHORIZATION_ENDPOINT}
      OAUTH_TOKEN_ENDPOINT: ${OAUTH_TOKEN_ENDPOINT}
      OAUTH_TOKEN_INTROSPECTION_ENDPOINT: ${OAUTH_TOKEN_INTROSPECTION_ENDPOINT}
      
      NODE_ENV: production
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "-e", "fetch('http://localhost:3001/health').then(r=>r.ok?process.exit(0):process.exit(1)).catch(()=>process.exit(1))"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1G
        reservations:
          cpus: '0.5'
          memory: 512M

# Nginx removed - using MCP server directly
# Add nginx back if you need SSL/custom domain later