[build]
builder = "nixpacks"

[deploy]
startCommand = "npm start"
numReplicas = 1
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
healthcheckPath = "/health"
healthcheckTimeout = 30
exposePort = 8080

# Environment variable configuration
[env]
# Transport configuration (MUST be http for Railway deployment)
TRANSPORT_MODE = "http"
NODE_ENV = "production"

# OAuth configuration (REQUIRED for remote MCP)
OAUTH_ENABLED = "true"

# All secrets are synced automatically from Doppler integration